spring:
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_UN}
    password: ${MYSQL_UNP}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
#    show-sql: true